---
- name: Install XFCE
  vars:
    packages:
      present:
        - xorg
        - lightdm
        - xfce4
        - xfce4-terminal
  include_role:
    name: install_packages

- name: Set default graphical target
  become: yes
  ansible.builtin.shell: systemctl set-default graphical.target

