---

- name: Import Sublime text GPG key
  become: yes
  community.general.pacman_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add repo source for Sublime text x86_64
  become: yes
  shell: echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf

- name: Arch Linux install packages
  become: yes
  pacman:
    update_cache: yes
    name: sublime-text
    state: present
