---
- name: Install GPG
  vars:
    packages:
      present:
        - gpg
        - gpg-agent
  include_role:
    name: install_packages

- name: Sublime text add GPG key
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime text repository into sources list using specified filename
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublimetext

- name: Debian install Sublime text
  become: yes
  apt:
    # Do not autostart services for installed packages
    policy_rc_d: 101
    update_cache: yes
    name: sublime-text
    state: present
    purge: yes
    install_recommends: no
    autoremove: yes
