---

- name: Docker add Debian GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository into sources list using specified filename
  become: yes
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker
  become: yes
  vars:
    packages:
      present:
        - docker-ce
        - docker
        - docker-compose
  include_role:
    name: install_packages
