---

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Install needed packages
  vars:
    packages:
      present:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
  include_role:
    name: install_packages

- name: Docker add Debian GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository into sources list using specified filename
  become: yes
  shell: rm /etc/apt/sources.list.d/docker.list || echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker
  vars:
    packages:
      present:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
  include_role:
    name: install_packages
