---

- include_tasks: "{{ ansible_distribution | lower }}.yml"

#- include: ubuntu.yml
#  when: ansible_facts['distribution'] == "Ubuntu"

#- include: debian.yml
#  when: ansible_facts['distribution'] == "Debian"
